-- Seed data for the Oracle schema.
-- Run after `database/schema.sql`.
-- This file focuses on system default data that the app expects.
-- Category names are kept in ASCII-safe form to avoid client encoding issues
-- on Oracle import tools.

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'An uong', 'EXPENSE', 'burger', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Di cho / Sieu thi', 'EXPENSE', 'cart', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Cafe / Tra sua', 'EXPENSE', 'drink', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'An ngoai / Nha hang', 'EXPENSE', 'restaurant', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Di chuyen', 'EXPENSE', 'car', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Di xe om / Taxi', 'EXPENSE', 'taxi', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Mua sam', 'EXPENSE', 'shopping', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Giai tri', 'EXPENSE', 'game', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Suc khoe', 'EXPENSE', 'health', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Lam dep', 'EXPENSE', 'beauty', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Tien nha / Dien nuoc', 'EXPENSE', 'home', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Internet / Dien thoai', 'EXPENSE', 'phone', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Hoc phi / Sach vo', 'EXPENSE', 'book', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Qua tang', 'EXPENSE', 'gift', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Ho tro gia dinh', 'EXPENSE', 'family', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Tiet kiem / Dau tu', 'EXPENSE', 'saving', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Luong chinh', 'INCOME', 'salary', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Thuong', 'INCOME', 'bonus', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Freelance / Lam them', 'INCOME', 'freelance', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Tien lai tiet kiem', 'INCOME', 'interest', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Tien qua / Cho vay', 'INCOME', 'gift-money', 1, NULL, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID, SOURCE_LOCAL_ID)
VALUES (COMMON_SEQ.NEXTVAL, 'Khac', 'INCOME', 'other', 1, NULL, NULL);

COMMIT;
