-- Oracle schema for the personal finance project.
-- Run this file on an empty Oracle schema before starting the backend.
-- The application itself currently uses Hibernate `ddl-auto=update`,
-- so this file is provided mainly for project submission and manual setup.

CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE COMMON_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE USERS (
    ID NUMBER(19,0) NOT NULL,
    USERNAME VARCHAR2(50 CHAR),
    EMAIL VARCHAR2(100 CHAR),
    PASSWORD_HASH VARCHAR2(255 CHAR),
    FULL_NAME VARCHAR2(100 CHAR),
    AVATAR_URL VARCHAR2(255 CHAR),
    PROVIDER_ID VARCHAR2(100 CHAR),
    PROVIDER VARCHAR2(50 CHAR),
    CREATED_AT TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USERS_PROVIDER_ID UNIQUE (PROVIDER_ID)
);

CREATE TABLE WALLETS (
    ID NUMBER(19,0) NOT NULL,
    USER_ID NUMBER(19,0) NOT NULL,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    INITIAL_BALANCE NUMBER(15,2) DEFAULT 0 NOT NULL,
    BALANCE NUMBER(15,2) DEFAULT 0 NOT NULL,
    CURRENCY VARCHAR2(10 CHAR) DEFAULT 'VND',
    SOURCE_LOCAL_ID VARCHAR2(120 CHAR),
    CREATED_AT TIMESTAMP,
    CONSTRAINT PK_WALLETS PRIMARY KEY (ID),
    CONSTRAINT FK_WALLETS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE CATEGORIES (
    ID NUMBER(19,0) NOT NULL,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    TYPE VARCHAR2(20 CHAR) NOT NULL,
    ICON VARCHAR2(50 CHAR),
    IS_DEFAULT NUMBER(1,0) DEFAULT 1 NOT NULL,
    USER_ID NUMBER(19,0),
    SOURCE_LOCAL_ID VARCHAR2(120 CHAR),
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID),
    CONSTRAINT FK_CATEGORIES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CK_CATEGORIES_TYPE CHECK (TYPE IN ('EXPENSE', 'INCOME')),
    CONSTRAINT CK_CATEGORIES_IS_DEFAULT CHECK (IS_DEFAULT IN (0, 1))
);

CREATE TABLE TRANSACTIONS (
    ID NUMBER(19,0) NOT NULL,
    WALLET_ID NUMBER(19,0) NOT NULL,
    AMOUNT NUMBER(15,2) NOT NULL,
    TYPE VARCHAR2(20 CHAR) NOT NULL,
    CATEGORY_ID NUMBER(19,0),
    NOTE CLOB,
    TRANSACTION_DATE TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP,
    VOICE_TEXT VARCHAR2(4000 CHAR),
    AI_RAW_RESPONSE CLOB,
    SOURCE_LOCAL_ID VARCHAR2(120 CHAR),
    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (ID),
    CONSTRAINT FK_TRANSACTIONS_WALLETS FOREIGN KEY (WALLET_ID) REFERENCES WALLETS (ID),
    CONSTRAINT FK_TRANSACTIONS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
    CONSTRAINT CK_TRANSACTIONS_TYPE CHECK (TYPE IN ('EXPENSE', 'INCOME')),
    CONSTRAINT CK_TRANSACTIONS_AMOUNT_POSITIVE CHECK (AMOUNT > 0)
);

CREATE TABLE AI_ADVICE_LOGS (
    ID NUMBER(19,0) NOT NULL,
    USER_ID NUMBER(19,0) NOT NULL,
    ADVICE_TEXT CLOB,
    GENERATED_AT TIMESTAMP,
    PERIOD VARCHAR2(20 CHAR),
    CONSTRAINT PK_AI_ADVICE_LOGS PRIMARY KEY (ID),
    CONSTRAINT FK_AI_ADVICE_LOGS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_WALLETS_USER_ID ON WALLETS (USER_ID);
CREATE INDEX IDX_WALLETS_USER_LOCAL_ID ON WALLETS (USER_ID, SOURCE_LOCAL_ID);

CREATE INDEX IDX_CATEGORIES_USER_ID ON CATEGORIES (USER_ID);
CREATE INDEX IDX_CATEGORIES_DEFAULT_TYPE ON CATEGORIES (IS_DEFAULT, TYPE);
CREATE INDEX IDX_CATEGORIES_USER_LOCAL_ID ON CATEGORIES (USER_ID, SOURCE_LOCAL_ID);

CREATE INDEX IDX_TRANSACTIONS_WALLET_ID ON TRANSACTIONS (WALLET_ID);
CREATE INDEX IDX_TRANSACTIONS_CATEGORY_ID ON TRANSACTIONS (CATEGORY_ID);
CREATE INDEX IDX_TRANSACTIONS_DATE ON TRANSACTIONS (TRANSACTION_DATE);
CREATE INDEX IDX_TRANSACTIONS_WALLET_DATE ON TRANSACTIONS (WALLET_ID, TRANSACTION_DATE);
CREATE INDEX IDX_TRANSACTIONS_SOURCE_LOCAL_ID ON TRANSACTIONS (SOURCE_LOCAL_ID);

CREATE INDEX IDX_AI_ADVICE_LOGS_USER_ID ON AI_ADVICE_LOGS (USER_ID);
CREATE INDEX IDX_AI_ADVICE_LOGS_PERIOD ON AI_ADVICE_LOGS (PERIOD);

COMMIT;
