-- Script để insert default categories vào database
-- Chạy script này để tạo categories mặc định cho hệ thống
-- Tổng 22 categories: 16 EXPENSE + 6 INCOME

-- ============================================
-- EXPENSE Categories (16 categories)
-- ============================================

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Ăn uống', 'EXPENSE', '🍔', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Đi chợ / Siêu thị', 'EXPENSE', '🛒', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Cafe / Trà sữa', 'EXPENSE', '🧋', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Ăn ngoài / Nhà hàng', 'EXPENSE', '🍽️', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Di chuyển', 'EXPENSE', '🚗', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Đi xe ôm / Taxi', 'EXPENSE', '🏍️', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Mua sắm', 'EXPENSE', '🛍️', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Giải trí', 'EXPENSE', '🎮', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Sức khỏe', 'EXPENSE', '💊', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Làm đẹp', 'EXPENSE', '💅', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Tiền nhà / Điện nước', 'EXPENSE', '🏠', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Internet / Điện thoại', 'EXPENSE', '📱', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Học phí / Sách vở', 'EXPENSE', '📚', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Quà tặng', 'EXPENSE', '🎁', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Hỗ trợ gia đình', 'EXPENSE', '👨‍👩‍👧‍👦', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Tiết kiệm / Đầu tư', 'EXPENSE', '💰', 1, NULL);

-- ============================================
-- INCOME Categories (6 categories)
-- ============================================

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Lương chính', 'INCOME', '💵', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Thưởng', 'INCOME', '🎉', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Freelance / Làm thêm', 'INCOME', '💼', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Tiền lãi tiết kiệm', 'INCOME', '📈', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Tiền quà / Cho vay', 'INCOME', '🎁', 1, NULL);

INSERT INTO CATEGORIES (ID, NAME, TYPE, ICON, IS_DEFAULT, USER_ID) 
VALUES (COMMON_SEQ.NEXTVAL, 'Khác', 'INCOME', '💸', 1, NULL);

COMMIT;
